name: Scrape 24x7

on:
  schedule:
    - cron: '*/5 * * * *'  # every 30 minutes

concurrency:
  group: scrape-group
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run scraper
        run: python main.py

      - name: Commit sheet_state.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sheet_state.json
          git diff --cached --quiet || git commit -m "Update sheet ID"
          git push
