name: Scrape 24x7

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:        # 👈 allows manual trigger from GitHub UI

concurrency:
  group: scrape-group
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run scraper
        run: python main.py

      - name: Confirm sheet_state.json was handled
        run: echo "✅ Sheet state handled inside Python script"
